name: issue-tracking-system-nextjs CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/issue-tracking-system-nextjs:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/issue-tracking-system-nextjs:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/issue-tracking-system-nextjs:latest
            docker stop issue-tracking-system-nextjs || true
            docker rm issue-tracking-system-nextjs || true
            docker run -d -p 80:3000 --name issue-tracking-system-nextjs \
            ${{ secrets.DOCKERHUB_USERNAME }}/issue-tracking-system-nextjs:latest
            sleep 10
            docker logs issue-tracking-system-nextjs
